#!/usr/bin/python3
from InsnSet import InsnSet
from Template import Template
#from Parititioner import Partitioner

iset = InsnSet("instructions.xml")

templates = [
	("cpu_stub.mako", "cpu_stub.c"),
	("decoder_c.mako", "decoder.c"),
	("decoder_h.mako", "decoder.h"),
	("implementation_c.mako", "implementation.c"),
	("implementation_h.mako", "implementation.h"),
]

for (infile, outfile) in templates:
	tmpl = Template(infile)
	output = tmpl.render(i = iset)
	open(outfile, "w").write(output)

