#!/usr/bin/python3
#	libthumb2sim - Emulator for the Thumb-2 ISA (Cortex-M)
#	Copyright (C) 2014-2019 Johannes Bauer
#
#	This file is part of libthumb2sim.
#
#	libthumb2sim is free software; you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation; this program is ONLY licensed under
#	version 3 of the License, later versions are explicitly excluded.
#
#	libthumb2sim is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with libthumb2sim; if not, write to the Free Software
#	Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#	Johannes Bauer <JohannesBauer@gmx.de>

from InsnSet import InsnSet
from Template import Template
#from Parititioner import Partitioner

iset = InsnSet("instructions.xml")

templates = [
	("cpu_stub.mako", "cpu_stub.c"),
	("decoder_c.mako", "decoder.c"),
	("decoder_h.mako", "decoder.h"),
	("implementation_c.mako", "implementation.c"),
	("implementation_h.mako", "implementation.h"),
]

for (infile, outfile) in templates:
	tmpl = Template(infile)
	output = tmpl.render(i = iset)
	open(outfile, "w").write(output)

